# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: swolfpy-processmodels

on:
  push:
    branches-ignore: []
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Check if feature branch exists in swolfpy-inputdata
      id: branch-check
      run: |
        if git ls-remote --exit-code --heads https://github.com/SwolfPy-Project/swolfpy-inputdata.git ${{ github.head_ref }}; then
          echo "Branch exists."
          echo "BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV
        else
          echo "Branch does not exist. Falling back to 'master' branch."
          echo "BRANCH=master" >> $GITHUB_ENV
        fi

    - name: Install swolfpy-inputdata from branch
      run: |
        echo ${{ env.BRANCH }}
        pip install git+https://github.com/SwolfPy-Project/swolfpy-inputdata.git@${{ env.BRANCH }}

    - name: Install rest of dependencies
      run: |
        pip install -r requirements.txt
